CREATE DATABASE sreality;
\c sreality;
CREATE USER luxonis WITH PASSWORD 'luxonis1';
GRANT ALL PRIVILEGES ON DATABASE sreality TO luxonis;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO luxonis;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO luxonis;