version: '3'

services:
  scrapy:
    build: .
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=sreality
      - POSTGRES_USER=luxonis
      - POSTGRES_PASSWORD=luxonis1
    command: postgres -c 'listen_addresses=*'
    restart: unless-stopped

  http_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./http_server:/app/http_server
    environment:
      - DOCKERIZED=True
    depends_on:
      - database
    restart: on-failure
